# fly.toml app configuration file generated for phonebook-fso-lsy on 2023-10-20T07:45:04+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebook-fso-lsy"
primary_region = "syd"

[build]

[env]
  PORT = "3000"
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
