POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Why I Am a Bad Correspondent",
    //"author": "Neal Stephenson",
    "url": "https://nealstephenson.com/why-i-am-a-bad-correspondent.html"
}